stages:
  mace-omol_L7Benchmark:
    cmd: zntrack run calc_L7.L7Benchmark --name mace-omol_L7Benchmark
    metrics:
    - nodes/mace-omol/L7Benchmark/node-meta.json:
        cache: true
    params:
    - mace-omol_L7Benchmark
